//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long OrderDetailID { get; set; }
        public long OrderNo { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public byte EditState { get; set; }
        public Nullable<int> EditAmount { get; set; }
        public bool NotEditable { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual Products Products { get; set; }
    }
}
