//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public OrderHeader()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.Payments = new HashSet<Payments>();
        }
    
        public long OrderNo { get; set; }
        public string TableNo { get; set; }
        public int CreatorUserID { get; set; }
        public System.DateTime CreationDatetime { get; set; }
        public Nullable<System.DateTime> LastEditionDatetime { get; set; }
        public string CustomerName { get; set; }
        public decimal TotalPrice { get; set; }
        public bool LockState { get; set; }
        public Nullable<int> LockKeeperUserID { get; set; }
        public bool PrintState { get; set; }
        public string CancelCause { get; set; }
        public byte State { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual RestaurantTables RestaurantTables { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
