//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public Nullable<long> OrderNo { get; set; }
        public Nullable<int> PaymentModuleID { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public System.DateTime Date { get; set; }
        public string Discount { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual PaymentModules PaymentModules { get; set; }
    }
}
