//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPurchases
    {
        public int PurchaseID { get; set; }
        public int SupplierID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
