//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string UnitName { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public decimal Price { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public bool Availability { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
    }
}
