//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.XtraEditors;

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public Purchases()
        {
            this.PurchaseDetail = new HashSet<PurchaseDetail>();
        }
    
        public int PurchaseID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> FicheTypeID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<decimal> TotalCash { get; set; }
        public string Description { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
    
        public virtual FicheTypes FicheTypes { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetail { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
