//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TableNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Cancel { get; set; }
        public Nullable<byte> Used { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual RestaurantTables RestaurantTables { get; set; }
        public virtual Users Users { get; set; }
    }
}
