//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWEN.DTO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.OrderHeader = new HashSet<OrderHeader>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte PermissionID { get; set; }
    
        public virtual ICollection<OrderHeader> OrderHeader { get; set; }
        public virtual Permissions Permissions { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
